AWSTemplateFormatVersion: 2010-09-09
Description: |
 cfn-101-kitten-project
  
# Parameters:
  
Resources: 
 cfn-instance-kitten:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: ami-0022f774911c1d690
    InstanceType: t2.micro
    KeyName: firstkey
    SecurityGroups:
      - cfn-sec-group
    Tags:
      - Key: Name 
        Value: Kittens_Carousel_Static
    UserData:
      
  
# Outputs: